FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg libgl1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . /app/

# 啟動 Celery Worker
CMD ["celery", "-A", "tasks", "worker", "--loglevel=info"]
