# python_crawlers/Dockerfile.celery
FROM python:3.9-slim
WORKDIR /app
RUN apt-get update && apt-get install -y ffmpeg
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
CMD ["celery", "-A", "workers.tasks", "worker", "--loglevel=info"]
